---
title: "An interdisciplinary examination of stress and injury occurrence in athletes"
runtitle: "Short Title"
documentclass: frontiersHLTH  # or frontiersHLTH, or frontiersFPHY
author:
  - name: Dr Harry Fisher
    affiliation: '1'
    etal: Fisher # First author's last name. 
    email: harryfisher21@gmail.com # Indicates corresponding Author
    institution: Cardiff Metropolitan University
    street: Cyncoed Road
    zip: CF23 6XD
    country: United Kingdom
  - name: Dr Marianne Gittoes
    affiliation: '1'
  - name: Professor Lynne Evans
    affiliation: '1'
  - name: Miss Leah Bitchell
    affiliation: '1'  
  - name: Dr Richard Mullen  
    affiliation: '2'
  - name: Dr Marco Scutari
    affiliation: '3'    
affiliation:
  - id: '1'
    department: School of Sport and Health Science
    institution: Cardiff Metropolitan University
    city: Cardiff
    country: United Kingdom
  - id: '2' 
    department: Division of Sport, Health & Exercise Sciences
    institution: Brunel University
    city: London
    country: United Kingdom
  - id: '3' 
    institution: Istituto Dalle Molle di Studi sull'Intelligenza Artificiale (IDSIA) 
    city: Manno
    country: Switzerland
    
output: rticles::frontiers_article
csl: frontiers.csl
bibliography: library.bib
---

\begin{abstract}

This paper adopts an interdisciplinary approach to explore the relationship between psychosocial factors, physiological stress-related markers and occurrence of injury in athletes using a repeated measures design across a 2-year data collection period. At three data collection time-points, athletes completed measures of major life events, the reinforcement sensitivity theory personality questionnaire, muscle stiffness, heart rate variability and postural stability, an
d reported any injuries they had sustained since the last data collection. Two Bayesian networks were used to examine the relationships between variables and model the changes between data collection points in the study. Findings revealed muscle stiffness to have the strongest relationship with injury occurrence, with high levels of stiffness increasing the probability of sustaining an injury. Negative life events did not increase the probability of injury occurrence at any single time-point; however, when examining changes between time points, increases in negative life events did increase the probability of injury. In addition, the combination of increases in negative life events and muscle stiffness resulted in the greatest probability of sustaining an injury. Findings demonstrated the importance of both an interdisciplinary approach and a repeated measures design to furthering our understanding of the relationship between stress-related  markers and injury occurrence.

\tiny
 \keyFont{ \section{Keywords:} Sports Injury, Stress, Interdisciplinary, Bayesian Network} 

\end{abstract}


```{r include=FALSE}
options(scipen=999, digits = 2)
knitr::opts_chunk$set(echo = FALSE)
#source("r-files/functions.R")
#source("r-files/methods_code.R")
#source("r-files/results_code.R")
```

# Introduction {-}

Over the last four decades sport related injuries have received increased research attention [@Ivarsson2017].
This attention is unsurprising given the high incidence [@Rosa2014; @Sheu2016],
and undesirable physical and psychological effects of sports injuries [@Leddy1994; @Brewer2012].
To mitigate against both the increasing incidence and	undesirable consequences of injury, research  has identified several psychological [@Slimani2018],
anatomical [@Murphy2003],
biomechanical [@Neely1998; @Hughes2014]
and environmental [@Meeuwisse2007]
factors associated with sports injury occurrence.
Indeed, several models of injury causation have been proposed that highlight the multifactorial nature of injury occurrence [@Kumar2001; @Meeuwisse2007; @Wiese-Bjornstal2009],
of which one of the most widely cited was developed by Williams and Anderson [Fig \ref{fig:fig1}; @Andersen1988; @Williams1998].

\begin{figure}[!h]
\caption{{\bf Stress and injury model (Williams and Andersen, 1998).}}
\label{fig:fig1}
\end{figure}

Williams and Andersen's [@Williams1998] model proposed that when faced with a potentially stressful athletic situation, an athlete’s personality traits (e.g., hardiness, locus of control and competitive trait anxiety), history of stressors (e.g., major life events and previous injuries) and coping resources (e.g., general coping behaviours) will contribute to their response, either interactively or in isolation.
Central to the model is the stress response, which reflects the bi-directional relationship between athletes’ appraisal of, and response to, a stressful athletic situation. The model predicts that athletes who have a history of many stressors, personality traits that intensify the stress response and few coping resources, will exhibit greater attentional (e.g., peripheral narrowing) and/or physiological (e.g., increased muscle tension) responses that put these individuals at greater risk of injury.

Within Williams and Andersen’s [@Williams1998] model, major life events, a component of an athlete’s history of stressors, most consistently predicts injury occurrence [@Williams2007];
specifically, major life events with a negative, as opposed to positive, valence [@Passer1983a; @Maddison2005].
However, personality traits and coping resources have also been	found to predict injury, with for example, athletes more likely to sustain an injury if they have poor social support and psychological coping skills, and high trait anxiety and elevated competitive state anxiety; compared to athletes with the opposite profile. [@Smith1990; @Lavallee1996; @Ivarsson2010].
However, the amount of variance explained by the psychosocial factors proposed by the model has been modest, typically between 5 - 30% [@Galambos2005; @Ivarsson2010]; suggesting other factors are also likely to contribute to injury occurrence.

While the psychosocial factors proposed in Williams and Andersen’s [@Williams1998] model have received the most research attention, the mechanisms through which these factors are proposed to exert their effect have remained under-investigated in the literature. 
To elaborate, the  model suggests that injuries are likely to occur through either increased physiological arousal resulting in increased muscle tension and reduced flexibility or attentional deficits caused by increased distractibility and peripheral narrowing.
However, to date, the research has largely focused on attentional deficits [@Andersen1999; @Rogers2005; @Wilkerson2012a; @Swanik2007].
For example, Andersen and Williams [@Andersen1999]
measured peripheral and central vision during high and low stress conditions and found athletes with high life event stress coupled with low social support had greater peripheral narrowing under stressful conditions compared to athletes with the opposing profile; these athletes went on to sustain an increased number of injuries during the following season.
Indeed, Rodgers and Landers [@Rogers2005] supported Andersen and Williams's [@Andersen1999] earlier findings reporting that peripheral narrowing under stress mediated 8.1% of the relationship between negative life events and injury.
However, the remaining variance between negative life events and athletic injury through the other proposed mechanisms, such as increased muscle tension and reduced motor control, remains to be explored [cf. @Williams1998].

One challenge faced by researchers addressing the sports injury problem with a psychological lens is the multifactorial nature of injury, and the possible contribution of other non-psychological factors to the stress response
[@Meeuwisse2007; @Wiese-Bjornstal2009].
For example, a large body of research indicates that training-related stress is also likely to be related to the stress response and injury occurrence [@Lee2017; @Djaoui2017],
and may account for the unexplained variance from the psychological predictors of injury.
Appaneal and Perna [@Appaneal2014]
proposed the biopsychosocial model of stress athletic injury and health (BMSAIH) to serve as an extension to Williams and Andersen’s [@Williams1998] model and to address some of these issues.
To elaborate, the BMSAIH aimed to clarify the mediating pathways between the stress response and injury, consider other health outcomes and behavioural factors that impact sports participation,
and integrate the impact of training on athletes’ health [@Appaneal2014].
The central tenet of the BMSAIH is that psychosocial distress (e.g., negative life events) may act synergistically with training-related stress as a result of high-intensity and high-volume sports training, and “widen the window of susceptibility” [@Appaneal2014, p. 74] to a range of undesirable health outcomes including illness and injury.
Consequently, the BMSAIH provides a framework for future research to build on Williams and Andersen's [@Williams1998] model, by including other physiological markers of training-related stress, which together may provide greater insight into the injury process.

Although research supporting the BMSAIH has mainly focused on the relationship between hormonal responses to training and injury occurrence [@Perna1995; @Perna1997; @Perna2003], other research has identified additional markers of training-related stress that are associated with an increased risk of injury; for example,
heart rate variability [@Bellenger2016; @Williams2017],
postural stability [@Romero-Franco2014]
and muscle stiffness [@Pruyn2015].
However, these markers are often studied in isolation without an assessment of the psychosocial factors that are known to contribute to injury, thereby limiting our understanding of how psychosocially and physiologically derived stress may contribute synergistically to injury occurrence.
Recently, Bittencourt et al. [@Bittencourt2016]
suggested that to better understand the multifactorial nature of sports injuries, research needs to move away from studying risk factors in isolation and instead adopt a complex systems approach to injury.
Such an approach posits that injury may arise from a complex “web of determinants” [@Bittencourt2016, p. 3],
where different factors interact in unpredictable and unplanned ways, but result in a global outcome pattern of either adaptation or injury.

A challenge when adopting a complex systems approach is using an appropriate analysis technique that is able to capture the uncertainty and complexity of the relationships between different variables. One technique that provides a solution to this challenge is Bayesian network (BN) modelling. BN's allow the construction of graphical probabilistic models using the underlying structure that connects different variables (nodes in the network) of interest [@Scutari2014]. Once constructed, the learned structure can be used for inference by obtaining the posterior probabilities of a particular node for a given query (e.g., if the value of Node A is x and the value of Node B is y, what is the probability Node C being value z?). Furthermore, BN's do not distinguish between dependent and independent variables as they are a form of unsupervised learning, which is a strength over regression or structure equation models when the underlying relationship in the network may not be known [@Olmedilla2018].

To summarise, despite offering a possible framework to build on the research stemming from Williams and Andersen's [@Williams1998] model, there remains and opportunity to explore other physiological stress-related markers proposed by the BMSAIH, in addition to the already well-established psychological characteristics known to be related to injury [@Appaneal2014].
Furthermore, research has typically not captured changes in both psychosocial factors and stress-related physiological markers that may occur between initial measurement and injury occurrence.
Given the exploratory nature of the current study the following objectives were defined:

- Identify suitable markers of stress that can be easily captured in a large cohort of athletes in a field based setting. 
- Examine the relationships between the markers of stress and injury using a prospective, repeated measures design.
- Evaluate the relationships between the markers of stress and injury using Bayesian network modelling that captures the complex nature of injury occurrence.
