---
title: "Untitled"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Despite the numerous physical, mental and social benefits of participating in sport, one of the more negative and arguably inevitable consequences, is injury. One important factor that has been linked to injury is stress. However sports science research has addressed the stress-injury relationship from a somewhat narrow perspective. The sub-disciplines of psychology, physiology and biomechanics have employed discipline specific approaches to examine factors associated with the stress-injury relationship – but rarely has this research gone beyond their disciplinary boundaries or included the multiple waves of measurement required to capture the dynamic nature of the stress-injury relationship. This study addresses those shortcomings by adopting an interdisciplinary approach and repeated measure design to investigate the relationships between psychological (major life events) and physiological measures of stress (muscle stiffness, heart rate variability and balance) to capture the multifaceted and dynamic nature of the stress- sports injury relationship. Findings revealed: the probability of injury was greatest when there was a combination of high muscle stiffness and poor balance  and increases in negative life event stress and muscle stiffness over time increased the probability of injury. These findings provide important insights that can enhance our understanding of the complex relationship between stress and injury.