---
title: "wordmaker"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Over the last four decades sport related injuries have received increased research attention [@Ivarsson2017].
This attention is unsurprising given the high incidence [@Rosa2014; @Sheu2016],
and undesirable physical and psychological effects of sports injuries [@Leddy1994; @Brewer2012].
To mitigate against both the increasing incidence and	undesirable consequences of injury, research  has identified several psychological [@Slimani2018],
anatomical [@Murphy2003],
biomechanical [@Neely1998; @Hughes2014]
and environmental [@Meeuwisse2007]
factors associated with sports injury occurrence.
Indeed, several models of injury causation have been proposed that highlight the multifactorial nature of injury occurrence [@Kumar2001; @Meeuwisse2007; @Wiese-Bjornstal2009],
of which one of the most widely cited was developed by Williams and Anderson [Fig \ref{fig:fig1}; @Andersen1988; @Williams1998].

\begin{figure}[!h]
\caption{{\bf Stress and injury model (Williams and Andersen, 1998).}}
\label{fig:fig1}
\end{figure}

Williams and Andersen's [@Williams1998] model proposed that when faced with a potentially stressful athletic situation, an athlete’s personality traits (e.g., hardiness, locus of control and competitive trait anxiety), history of stressors (e.g., major life events and previous injuries) and coping resources (e.g., general coping behaviours) will contribute to their response, either interactively or in isolation.
Central to the model is the stress response, which reflects the bi-directional relationship between athletes’ appraisal of, and response to, a stressful athletic situation. The model predicts that athletes who have a history of many stressors, personality traits that intensify the stress response and few coping resources, will exhibit greater attentional (e.g., peripheral narrowing) and/or physiological (e.g., increased muscle tension) responses that put these individuals at greater risk of injury.

Within Williams and Andersen’s [@Williams1998] model, major life events, a component of an athlete’s history of stressors, most consistently predicts injury occurrence [@Williams2007];
specifically, major life events with a negative, as opposed to positive, valence [@Passer1983a; @Maddison2005].
However, personality traits and coping resources have also been	found to predict injury, with for example, athletes more likely to sustain an injury if they have poor social support and psychological coping skills, and high trait anxiety and elevated competitive state anxiety; compared to athletes with the opposite profile. [@Smith1990; @Lavallee1996; @Ivarsson2010].
However, the amount of variance explained by the psychosocial factors proposed by the model has been modest, typically between 5 - 30% [@Galambos2005; @Ivarsson2010]; suggesting other factors are also likely to contribute to injury occurrence.

While the psychosocial factors proposed in Williams and Andersen’s [@Williams1998] model have received the most research attention, the mechanisms through which these factors are proposed to exert their effect have remained under-investigated in the literature. 
To elaborate, the  model suggests that injuries are likely to occur through either increased physiological arousal resulting in increased muscle tension and reduced flexibility or attentional deficits caused by increased distractibility and peripheral narrowing.
However, to date, the research has largely focused on attentional deficits [@Andersen1999; @Rogers2005; @Wilkerson2012a; @Swanik2007].
For example, Andersen and Williams [@Andersen1999]
measured peripheral and central vision during high and low stress conditions and found athletes with high life event stress coupled with low social support had greater peripheral narrowing under stressful conditions compared to athletes with the opposing profile; these athletes went on to sustain an increased number of injuries during the following season.
Indeed, Rodgers and Landers [@Rogers2005] supported Andersen and Williams's [@Andersen1999] earlier findings reporting that peripheral narrowing under stress mediated 8.1% of the relationship between negative life events and injury.
However, the remaining variance between negative life events and athletic injury through the other proposed mechanisms, such as increased muscle tension and reduced motor control, remains to be explored [cf. @Williams1998].